Criar novas contas - Página de Registro
arthurzeras/expenses pull request #2
Opened 2020-08-26 23:39 UTC by Gousro

- Criei uma página que cria novas contas de usuários;
- Na Página de _Login_, criei um link para a Página de Registro;
- Alterei o _router_ para que a Página de Registro possa ser acessada, já que tem uma regra que usuários não _logados_ é redirecionado para Página de _login_;
- Escondi o link da Página de Registro do menu _nav_;
- Atualizei as dependências pois estavam desatualizadas e cheias de vulnerabilidades;
- Atualizei o arquivo README com as informações novas de versões das dependências e criei um _table of contents_ para navegar pelo README.

2020-08-27 01:12 UTC, arthurzeras commented on src/components/layout/LayoutNavigation.vue
> +/* eslint-disable space-before-function-paren */
Como já tem uma regra de eslint para padronizar o código do projeto, não é uma boa desativá-las para esses casos, apenas em algo muuito específico mesmo.

2020-08-27 01:15 UTC, arthurzeras commented on src/pages/register/Register.vue
> +          .createUserWithEmailAndPassword(this.email, this.password);
Esse método retorna uma promise, temos que usar o `async/await` nesse caso, e colocar dentro de um `try catch` para tratar erros

2020-08-27 01:17 UTC, arthurzeras commented on src/pages/register/Register.vue
> +      .onAuthStateChanged((user) => (this.authenticatedUser = user));
Já existe o `onAuthStateChanged` no arquivo `src/App.vue`, acho que não tem necessidade de usar aqui de novo.

2020-08-27 01:17 UTC, arthurzeras commented on src/router.js
> +      component: () => import(/* webpackChunkName: "login" */ './pages/register/Register')
Alterar o nome do `chunk` de "login" para "register", para não ficar dois chunks iguais no momento de compilação

2020-08-27 01:20 UTC, arthurzeras requested changes
Muito bom @Gousro acho bem válido a implementação, ficou bacana demais, só mesmo ajustar essas regras de eslint pra usar a `Standard` que é a escolhida para esse projeto, no mais muito bom.

2020-08-27 18:37 UTC, Aetherista reviewed
- [x] Revisei.

**Plus:**
+ Adicionei validação e notificações para o registro.

2020-08-28 02:09 UTC, arthurzeras requested changes

2020-08-28 02:09 UTC, arthurzeras commented on src/pages/register/Register.vue
> +        console.log(err)
Acho que deixou o console log passar batido hehe 😅

2020-08-28 03:41 UTC, Aetherista reviewed
- [x] Fixed

Sempre tem algo que fica pra trás 😆

2020-08-28 11:37 UTC, merged